[package]
edition = "2021"
name = "napi-rs_ttf2woff2"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi3"] }
napi-derive = { version = "2" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
brotli-ffi = { path = "./brotli/c" }

[build-dependencies]
napi-build = "2"
cc = "1"

[profile.release]
lto = true
codegen-units = 1
